import re
GREEN = "\033[32m"
RED   = "\033[31m"
RESET = "\033[0m"

def is_valid_token(token):
	return (token in ('F', 'L', 'R')
		or re.fullmatch(r'[FLR][1-9]\d*|[FLR]0', token)
		or re.fullmatch(r'\(|\)|\)\d+', token)
		or re.fullmatch(r'p\d+', token)
		or re.fullmatch(r'P\d+', token)
		or token == 'q')

def expand_patterns(code, pattern_dict, index, call_stack=None):
	if call_stack is None:
		call_stack = {}
	def replace_match(match):
		pid = int(match.group(1))
		if (index == 0 or pid in pattern_dict):
			if pid not in pattern_dict:
				raise Exception(f"Pattern {pid} not defined")
			call_stack[pid] = call_stack.get(pid, 0) + 1
			if call_stack[pid] > 10 and index == 1:
				return match.group(0)
			elif call_stack[pid] > 10:
				raise Exception(f"Infinite recursion detected in pattern {pid}")
			expanded = expand_patterns(pattern_dict[pid], pattern_dict, index, call_stack)
			call_stack[pid] -= 1
		else:
			return match.group(0)
		return expanded
	return re.sub( r'P(\d+)', replace_match, code)

def get_pattern(code):
	bracket_not_closed = 0
	lvl = 1
	pattern = {}
	i = 1
	n = len(code)
	end = i
	if not code[i].isdigit():
		raise Exception("Invalid pattern declaration, missing id")
	while end < n and code[end].isdigit():
		end += 1
	if i == n:
		raise Exception("Invalid pattern declaration, empty pattern")
	id = int(code[i:end])
	i = end
	local_pattern = False
	while end < n and lvl != 0:
		if code[end] == ')':
			bracket_not_closed -= 1
		elif code[end] == '(':
			bracket_not_closed += 1
		elif code[end] == 'q':
			lvl -= 1
		elif code[end] == 'p':
			lvl += 1
			local_pattern = True
		end += 1
	if lvl != 0:
		raise Exception("Invalid pattern declaration, not closed by 'q'")
	if (local_pattern):
		pattern[id] = remove_patterns(code[i:end - 1], 1)
	else:
		pattern[id] = code[i:end - 1]
	if (bracket_not_closed):
			raise Exception("brackets not closed properly")
	return pattern, end

def remove_patterns(code, index=0):
	zero_seq = code.find(')0')
	while zero_seq != -1:
		start = zero_seq - 1
		while code[start] != '(':
			start -= 1
		code = code[:start] + code[zero_seq + 2:]
		zero_seq = code.find(')0')
	print(f"{GREEN}code send in remove_patterns{RESET} = ", end='')
	for c in code:
		if c == 'p':
			print(f"{GREEN}{c}", end='')
		elif c == 'q':
			print(f"{RED}{c}{RESET}", end='')
		else:
			print(f"{c}{RESET}", end='')
	print('\n')
	i = 0
	pattern_dict = {}
	output = []
	while i < len(code):
		if code[i] == 'p':
			new_patterns, j = get_pattern(code[i:])
			i += j
			for id in new_patterns:
				if id in pattern_dict:
					raise Exception(f"Pattern {id} is defined more than once")
			pattern_dict.update(new_patterns)
		else:
			output.append(code[i])
			i += 1
	return expand_patterns(''.join(output), pattern_dict, index)

def full_string(code):
	return re.sub(r'(.)\d+', lambda m: m[1] * int(m[0][1:]), code)

def find_brackets(code):
	i = code.rfind('(')
	if i == -1:
		return None, None
	lvl = 1
	for j in range(i + 1, len(code)):
		if code[j] == '(':
			lvl += 1
		elif code[j] == ')':
			lvl -= 1
			if not lvl:
				return i, j
	return None, None

def RS2_decode(code):
	while '(' in code:
		i, j = find_brackets(code)
		if i == None:
			break
		k = j + 1
		while k < len(code) and code[k].isdigit():
			k += 1
		n = int(code[j+1:k] or 1)
		code = code[:i] + full_string(code[i+1:j]) * n + code[k:]
	return full_string(code)

class RSUProgram:
	def __init__(self, source: str):
		self.source = source
	
	def execute_raw(self, raw_cmd):
		code = ''.join(raw_cmd)
		grid = [['*']]
		x = y = 0
		d = 0
		dirs = [(1,0),(0,1),(-1,0),(0,-1)]
		for c in code:
			if c == 'L':
				d = (d - 1) % 4
			elif c == 'R':
				d = (d + 1) % 4
			else:
				dx, dy = dirs[d]
				x += dx
				y += dy
				if y < 0:
					grid.insert(0, [' '] * len(grid[0]))
					y = 0
				if y == len(grid):
					grid.append([' '] * len(grid[0]))
				if x < 0:
					for r in grid: r.insert(0, ' ')
					x = 0
				if x == len(grid[0]):
					for r in grid: r.append(' ')
				grid[y][x] = '*'
		return '\r\n'.join(''.join(r) for r in grid)

	def convert_to_raw(self, tokens):
		code = ''.join(tokens)
		i = len(code)
		while i > 0:
			i, j = find_brackets(code[:i])
			if i == None:
				break
			if j + 1 < len(code) and code[j + 1] != '0':
				in_brackets = code[i + 1:j]
				matches = re.findall(r'[pP](\d+)', in_brackets)
				for pid in matches:
					p_pos = in_brackets.find('p' + pid)
					if p_pos != -1:
						if in_brackets.find('P' + pid, p_pos + 1) == -1:
							raise Exception("Pattern definitions cannot be nested inside bracketed sequences")
		decoded = ''.join(c for c in (RS2_decode(remove_patterns(code) if ('p' in code or 'P' in code) else code)))
		return list(decoded.replace('(', '').replace(')', ''))


	def get_tokens(self):
		print(f"------ source :\n{self.source}\n")
		code = self.source
		n = len(self.source)
		i = 0
		tokens = []
		while i < n:
			if code[i] in "FLRPp)":
				start = i
				i += 1
				while i < n and code[i].isdigit():
					i += 1
				str_int = code[start + 1:i]
				if code[start] in 'pP' and not str_int:
					raise Exception("pattern declaration without an identifier")
				elif len(str_int) > 1 and str_int[0] == '0':
					raise Exception("integer postfixes with leading zeroes")
				tokens.append(code[start:i])
			elif code[i:i + 2] == '/*':
				i+= 2
				while i < n and code[i:i + 2] != '*/':
					i += 1
				if i == n or (i + 2 < n and code[i:i + 2] != '*/'):
					raise Exception("Wrong comment")
				i += 2
				if i < n and code[i].isdigit():
					raise Exception("Comment before number")
			elif code[i:i + 2] == '//':
				i+= 2
				while i < n and code[i] != '\n':
					i += 1
				if i + 1 < n and code[i] == '\n' and code[i + 1].isdigit():
					raise Exception("Comment before number")
			elif code[i] == 'q' or code[i] == '(' or code[i].isspace():
				if not code[i].isspace():
					tokens.append(code[i])
				i += 1
			elif code[i].isdigit():
				raise Exception("Stray number")
			else:
				raise Exception(f"Illegal character : {code[i]}")
		print(f"tokens = {tokens}")
		return tokens
	
	def execute(self):
		return self.execute_raw(self.convert_to_raw(self.get_tokens()))

fail_on = """ p500801
  p309985
    R L L14 F0 R R3 R8 R8 R R17
  q
  p863810
    L15 R F R R5 F R15 F L9 F9
  q
  p421966
    L6 F R13 L F14 L L10 L F R
  q
  p303600
    R18 L14 L R7 F16 R12 F F7 R17 R
  q
  p530685
    R R6 L6 R R F F R12 R R
  q
  
  R16 R18 P421966 L2 F R (
    R L14 F F10 R3 R6 L L10 R4 R
  ) F5 R9 (
    F11 L R R F13 L F14 L17 F7 L
  )
q
p783459
  p787571
    R4 L F R4 L15 L3 L L L5 F
  q
  p6485
    F3 R19 L R R L7 R F11 L R0
  q
  p612533
    R1 R1 R L2 R L R4 R16 L14 R5
  q
  p224889
    F6 L7 F L4 L10 R0 F F F F
  q
  p522972
    F8 F9 L R9 R R3 L F L R
  q
  
  L L14 R (
    R17 F L0 F17 R16 F18 R19 R17 R R4
  )0 R (
    F R L R8 L2 L L3 R12 R18 F
  )5 (
    R L6 R R R F L R11 L18 R
  )10 R7 (
    R9 F L11 F L R F13 R F5 L
  )12 (
    R R19 F9 L L9 R L L13 L F12
  )16
q
p868725
  p398240
    F5 L11 R9 F18 L17 R3 F L14 R2 F
  q
  p101457
    L9 L16 L4 F R18 F R13 F L17 F11
  q
  p671804
    R16 L9 L R F10 L L F2 R5 R14
  q
  
  F15 (
    F8 L L F F7 L L6 R L F
  )12 F0 F6 (
    F F L F R10 F0 F F7 F9 F8
  ) P671804 L L1 (
    R L11 F10 F L4 F F R9 F15 L
  ) F
q

(
  F (
    F3 F L5 L R5 F R F1 R F
  ) F9 (
    F R F F11 L12 R16 L4 R9 F1 R
  )8 L L L R F (
    R L F F14 L1 L16 R19 L F5 R
  )
) P868725 (
  L L4 L9 (
    R16 L L F F16 R18 L L F6 L
  ) L R L17 R R R12
)0 L R (
  R7 F19 R2 L F L5 R9 R (
    F L R F17 L R8 L19 F6 F L19
  ) F18
) (
  (
    L10 R R R R F L R7 F R14
  ) R17 L16 F8 R17 R19 L (
    R R13 L19 L18 L F R R4 L3 F
  )17 L (
    R F13 F1 R16 F R11 F16 R F11 F
  )



  
)10 (
  R3 L (
    F F F F13 F F L R L5 F11
  )9 L15 L16 (
    R17 F R F18 R R R10 L14 R L
  ) L L F F19
)4 F4 L """
code = """FFFFFLLLLLLRRRRRFRFRFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRFRFFFFFFFFFFFFLLLLLLLLLLLLRRRRRRRRRRRRRRRRLLLLRRRRRRRRRFRLLLRFRLFFFFFFFFFFFFFFFLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRRRLFFFFFRFFFFFFFFFFFFFFFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLLFFFFFFFFLLLLLLLRLFFFFFFFFFLFRRRRRRRRRRFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRLLLLLLLLLLRFFFFFFFFFFLLFFRRRRRRRRRRRRRRRRRRRLLRLLLLLLLLLLLFFFFFFFFFFFLLLLFFRRRRRRRRRFFFFFFFFFFFFFFFLFLRRRRRRRRFFFFFFFFFFFFFFFFFFFRRLFLLLLLRRRRRRRRRRFLRFFFFFFFFFFFFFFFFFLRRRRRRRRLLLLLLLLLLLLLLLLLLLFFFFFFFLLLLLLLLLLLLLLLLLLLFFFFFFFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFLLLLLLLLLLRRRRFLRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLFFFFFFFFRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFRRRRRRRRRRRRRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLFRRRRRLLLFLRFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRFRRRRRRRRRRRFFFFFFFFFFFFFFFFRFFFFFFFFFFFFRRRLFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRFRFFFFFFFFFFFFFFFFFFRRRRRRRRRRRRLLLLLLLLLLLLLLRLLLFFFFFFFFFFFFFFFFFFFFRRRLFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRFRFFFFFFFFFFFFFFFFFFRRRRRRRRRRRRLLLLLLLLLLLLLLRLLLFFFFFFFFFFFFFFFFFFFFRRRLFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRFRFFFFFFFFFFFFFFFFFFRRRRRRRRRRRRLLLLLLLLLLLLLLRLLLFFFFFFFFFFFFFFFFFFFFRRRLFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFFFFFFFFFFFFFFFFFFFLRLLLLLFFFFFFFFFFFLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRFRFFFFFFFFFFFFFFFFFFRRRRRRRRRRRRLLLLLLLLLLLLLLRLLLFFFFFFFFFFFFFFFFFFFFFFFFL"""
program = RSUProgram(fail_on)
tokens = program.get_tokens()
print(tokens)
raw = program.convert_to_raw(tokens)
print(f"raw :\n{raw}")
expected = list(code)
if raw == expected:
    print("Congratulations ! it works as expected 🎉")
else:
    print("Wrong ❌")

    # longueur minimale comparable
    min_len = min(len(raw), len(expected))

    # trouver le premier index différent
    diff_index = None
    for i in range(min_len):
        if raw[i] != expected[i]:
            diff_index = i
            break

    if diff_index is None:
        print("Difference only in length")
        print(f"Expected length: {len(expected)}")
        print(f"Raw length     : {len(raw)}")
    else:
        context = 20  # nombre de caractères autour
        start = max(0, diff_index - context)
        end = diff_index + context

        print(f"First difference at index {diff_index}")
        print(f"Expected [{start}:{end}]: {expected[start:end]}")
        print(f"Raw      [{start}:{end}]: {raw[start:end]}")

    print(f"Total length difference: {len(raw) - len(expected)}")

exec = program.execute_raw(raw)
print(exec)
expected = program.execute_raw(expected)
if exec == expected:
	print("Congratulations ! it works as expected")
else:
	print(f"Wrong !\nexpecting :\n{expected}")

# print("-" * 20)
# exec = program.execute()
# print(exec)
# expected = exec
# if exec == expected:
# 	print("Congratulations ! it works as expected")
# else:
# 	print(f"Wrong !\nexpecting :\n{expected}")